# Generated by Django 5.2.11 on 2026-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoemSound',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filepath', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('download_url', models.TextField(blank=True, db_column='dnldurl', null=True)),
                ('is_direct', models.BigIntegerField(blank=True, db_column='isdirect', null=True)),
                ('sync_guid', models.TextField(blank=True, db_column='syncguid', null=True)),
                ('file_checksum', models.TextField(blank=True, db_column='fchksum', null=True)),
                ('is_uploaded', models.BigIntegerField(blank=True, db_column='isuploaded', null=True)),
            ],
            options={
                'verbose_name': 'poem sound',
                'verbose_name_plural': 'poem sounds',
                'db_table': 'poemsnd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoundSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_order', models.BigIntegerField(blank=True, null=True)),
                ('milisec', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sound sync point',
                'verbose_name_plural': 'sound sync points',
                'db_table': 'sndsync',
                'managed': False,
            },
        ),
    ]
