# Generated by Django 5.2.11 on 2026-03-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE cat SET parent_id = NULL WHERE parent_id = 0;

                ALTER TABLE poemsnd ALTER COLUMN id SET NOT NULL;
                ALTER TABLE poemsnd ALTER COLUMN poem_id SET NOT NULL;
                ALTER TABLE verse ALTER COLUMN poem_id SET NOT NULL;
                ALTER TABLE verse ALTER COLUMN vorder SET NOT NULL;
                ALTER TABLE poet ALTER COLUMN cat_id SET NOT NULL;

                CREATE INDEX IF NOT EXISTS idx_cat_poet_id ON cat (poet_id);
                CREATE INDEX IF NOT EXISTS idx_poet_cat_id ON poet (cat_id);
                CREATE INDEX IF NOT EXISTS idx_poemsnd_poem_id ON poemsnd (poem_id);
                CREATE INDEX IF NOT EXISTS idx_verse_poem_vorder ON verse (poem_id, vorder);
                CREATE INDEX IF NOT EXISTS idx_sndsync_snd_id ON sndsync (snd_id);
                CREATE INDEX IF NOT EXISTS idx_sndsync_poem_verse_order ON sndsync (poem_id, verse_order);
                CREATE INDEX IF NOT EXISTS idx_gil_cat_id ON gil (cat_id);

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'poemsnd_pkey'
                    ) THEN
                        ALTER TABLE poemsnd ADD CONSTRAINT poemsnd_pkey PRIMARY KEY (id);
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'uniq_verse_poem_vorder'
                    ) THEN
                        ALTER TABLE verse ADD CONSTRAINT uniq_verse_poem_vorder UNIQUE (poem_id, vorder);
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_cat_poet'
                    ) THEN
                        ALTER TABLE cat
                            ADD CONSTRAINT fk_cat_poet
                            FOREIGN KEY (poet_id) REFERENCES poet (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE cat VALIDATE CONSTRAINT fk_cat_poet;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_cat_parent'
                    ) THEN
                        ALTER TABLE cat
                            ADD CONSTRAINT fk_cat_parent
                            FOREIGN KEY (parent_id) REFERENCES cat (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE cat VALIDATE CONSTRAINT fk_cat_parent;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_poet_cat'
                    ) THEN
                        ALTER TABLE poet
                            ADD CONSTRAINT fk_poet_cat
                            FOREIGN KEY (cat_id) REFERENCES cat (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE poet VALIDATE CONSTRAINT fk_poet_cat;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_poem_cat'
                    ) THEN
                        ALTER TABLE poem
                            ADD CONSTRAINT fk_poem_cat
                            FOREIGN KEY (cat_id) REFERENCES cat (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE poem VALIDATE CONSTRAINT fk_poem_cat;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_verse_poem'
                    ) THEN
                        ALTER TABLE verse
                            ADD CONSTRAINT fk_verse_poem
                            FOREIGN KEY (poem_id) REFERENCES poem (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE verse VALIDATE CONSTRAINT fk_verse_poem;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_poemsnd_poem'
                    ) THEN
                        ALTER TABLE poemsnd
                            ADD CONSTRAINT fk_poemsnd_poem
                            FOREIGN KEY (poem_id) REFERENCES poem (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE poemsnd VALIDATE CONSTRAINT fk_poemsnd_poem;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_sndsync_poem'
                    ) THEN
                        ALTER TABLE sndsync
                            ADD CONSTRAINT fk_sndsync_poem
                            FOREIGN KEY (poem_id) REFERENCES poem (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE sndsync VALIDATE CONSTRAINT fk_sndsync_poem;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_sndsync_snd'
                    ) THEN
                        ALTER TABLE sndsync
                            ADD CONSTRAINT fk_sndsync_snd
                            FOREIGN KEY (snd_id) REFERENCES poemsnd (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE sndsync VALIDATE CONSTRAINT fk_sndsync_snd;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fk_gil_cat'
                    ) THEN
                        ALTER TABLE gil
                            ADD CONSTRAINT fk_gil_cat
                            FOREIGN KEY (cat_id) REFERENCES cat (id) NOT VALID;
                    END IF;
                END $$;
                ALTER TABLE gil VALIDATE CONSTRAINT fk_gil_cat;
            """,
            reverse_sql="""
                ALTER TABLE IF EXISTS gil DROP CONSTRAINT IF EXISTS fk_gil_cat;
                ALTER TABLE IF EXISTS sndsync DROP CONSTRAINT IF EXISTS fk_sndsync_snd;
                ALTER TABLE IF EXISTS sndsync DROP CONSTRAINT IF EXISTS fk_sndsync_poem;
                ALTER TABLE IF EXISTS poemsnd DROP CONSTRAINT IF EXISTS fk_poemsnd_poem;
                ALTER TABLE IF EXISTS verse DROP CONSTRAINT IF EXISTS fk_verse_poem;
                ALTER TABLE IF EXISTS poem DROP CONSTRAINT IF EXISTS fk_poem_cat;
                ALTER TABLE IF EXISTS poet DROP CONSTRAINT IF EXISTS fk_poet_cat;
                ALTER TABLE IF EXISTS cat DROP CONSTRAINT IF EXISTS fk_cat_parent;
                ALTER TABLE IF EXISTS cat DROP CONSTRAINT IF EXISTS fk_cat_poet;
                ALTER TABLE IF EXISTS verse DROP CONSTRAINT IF EXISTS uniq_verse_poem_vorder;
                ALTER TABLE IF EXISTS poemsnd DROP CONSTRAINT IF EXISTS poemsnd_pkey;
                DROP INDEX IF EXISTS idx_gil_cat_id;
                DROP INDEX IF EXISTS idx_sndsync_poem_verse_order;
                DROP INDEX IF EXISTS idx_sndsync_snd_id;
                DROP INDEX IF EXISTS idx_verse_poem_vorder;
                DROP INDEX IF EXISTS idx_poemsnd_poem_id;
                DROP INDEX IF EXISTS idx_poet_cat_id;
                DROP INDEX IF EXISTS idx_cat_poet_id;
                ALTER TABLE poemsnd ALTER COLUMN poem_id DROP NOT NULL;
                ALTER TABLE poemsnd ALTER COLUMN id DROP NOT NULL;
                ALTER TABLE verse ALTER COLUMN poem_id DROP NOT NULL;
                ALTER TABLE verse ALTER COLUMN vorder DROP NOT NULL;
                ALTER TABLE poet ALTER COLUMN cat_id DROP NOT NULL;
            """,
        ),
    ]
