# Generated by Django 5.2.11 on 2026-03-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_harden_ganjoor_schema'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE verse ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE sndsync ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE fav ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE gil ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE gver ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'verse_pkey'
                    ) THEN
                        ALTER TABLE verse ADD CONSTRAINT verse_pkey PRIMARY KEY (id);
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'sndsync_pkey'
                    ) THEN
                        ALTER TABLE sndsync ADD CONSTRAINT sndsync_pkey PRIMARY KEY (id);
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'fav_pkey'
                    ) THEN
                        ALTER TABLE fav ADD CONSTRAINT fav_pkey PRIMARY KEY (id);
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'gil_pkey'
                    ) THEN
                        ALTER TABLE gil ADD CONSTRAINT gil_pkey PRIMARY KEY (id);
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'gver_pkey'
                    ) THEN
                        ALTER TABLE gver ADD CONSTRAINT gver_pkey PRIMARY KEY (id);
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE IF EXISTS gver DROP CONSTRAINT IF EXISTS gver_pkey;
                ALTER TABLE IF EXISTS gil DROP CONSTRAINT IF EXISTS gil_pkey;
                ALTER TABLE IF EXISTS fav DROP CONSTRAINT IF EXISTS fav_pkey;
                ALTER TABLE IF EXISTS sndsync DROP CONSTRAINT IF EXISTS sndsync_pkey;
                ALTER TABLE IF EXISTS verse DROP CONSTRAINT IF EXISTS verse_pkey;
                ALTER TABLE IF EXISTS gver DROP COLUMN IF EXISTS id;
                ALTER TABLE IF EXISTS gil DROP COLUMN IF EXISTS id;
                ALTER TABLE IF EXISTS fav DROP COLUMN IF EXISTS id;
                ALTER TABLE IF EXISTS sndsync DROP COLUMN IF EXISTS id;
                ALTER TABLE IF EXISTS verse DROP COLUMN IF EXISTS id;
            """,
        ),
    ]
