# Generated by Django 5.2.11 on 2026-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_id', models.BigIntegerField(blank=True, null=True)),
                ('verse_id', models.BigIntegerField(blank=True, null=True)),
                ('pos', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'db_table': 'fav',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GanjoorVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.BigIntegerField(blank=True, db_column='curver', null=True)),
            ],
            options={
                'verbose_name': 'ganjoor version',
                'verbose_name_plural': 'ganjoor versions',
                'db_table': 'gver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IgnoredCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ignored category',
                'verbose_name_plural': 'ignored categories',
                'db_table': 'gil',
                'managed': False,
            },
        ),
    ]
