"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from django.utils.translation import gettext_lazy as _

from config import envs


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = envs.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = envs.DEBUG

ALLOWED_HOSTS = envs.ALLOWED_HOSTS

CSRF_TRUSTED_ORIGINS = envs.CSRF_TRUSTED_ORIGINS

INTERNAL_IPS = [
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'debug_toolbar',
    'rest_framework',
    'django_celery_beat',
    'drf_spectacular',
    'cacheops',

    # Django Apps
    'common.apps.CommonConfig',
    'account.apps.AccountConfig',
    'content.apps.ContentConfig',
    'audio.apps.AudioConfig',
    'meta.apps.MetaConfig',

    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': envs.POSTGRES_DB,
        'USER': envs.POSTGRES_USER,
        'PASSWORD': envs.POSTGRES_PASSWORD,
        'HOST': envs.POSTGRES_HOST,
        'PORT': envs.POSTGRES_PORT,
        'CONN_MAX_AGE': envs.DB_CONN_MAX_AGE,
    }
}

# Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': envs.REDIS_SERVER_URL(db=0),
    }
}

CACHEOPS_REDIS = envs.REDIS_SERVER_URL(db=0)
LONG_CACHE_TIMEOUT = 60 * 60 * 24 * 7  # 7 Days
CACHEOPS_DEFAULTS = {
    'timeout': 60 * 60 * (envs.CACHE_TIMEOUT_HOURS or 5)
}
CACHEOPS = {
    'content.Poem': {
        'timeout': LONG_CACHE_TIMEOUT
    },
    'content.Poet': {
        'timeout': LONG_CACHE_TIMEOUT
    },
    'content.Category': {
        'timeout': LONG_CACHE_TIMEOUT
    },
    'content.Verse': {
        'timeout': LONG_CACHE_TIMEOUT
    },
    'content.PoemSound': {
        'timeout': LONG_CACHE_TIMEOUT
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'account.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = (
    ('fa', _('Persian')),
    ('en-us', _('English')),
)

LOCALE_PATHS = (
    BASE_DIR / 'templates' / 'locale',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TESTING = 'test' in sys.argv

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

# DRF Spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': envs.PROJECT_TITLE,
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'DISABLE_ERRORS_AND_WARNINGS': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'CAMELIZE_NAMES': True,
    'SERVE_AUTHENTICATION': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'SERVE_PERMISSIONS': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# Celery configuration
CELERY_BROKER_URL = envs.MESSAGE_BROKER_URL
CELERY_RESULT_BACKEND = envs.REDIS_SERVER_URL(db=1)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {}

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_TIME_LIMIT = 60 * 60 * 2  # Maximum hard limit (in seconds) for tasks
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 60 * 1  # Warning time limit before the task is killed

# Celery Queue Configuration
CELERY_TASK_QUEUES = {}

# Task routing
CELERY_TASK_ROUTES = {}

# Optimize task prefetch
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Disable prefetching for better resource management
CELERY_TASK_ACKS_LATE = True  # Only acknowledge tasks after they are completed


# Storage
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 Mb limit
