# Generated by Django 5.2.11 on 2026-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'poem',
                'verbose_name_plural': 'poems',
                'db_table': 'poem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'poet',
                'verbose_name_plural': 'poets',
                'db_table': 'poet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(db_column='vorder')),
                ('position', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'verse',
                'verbose_name_plural': 'verses',
                'db_table': 'verse',
                'managed': False,
            },
        ),
    ]
