# Generated by Django 5.2.11 on 2026-03-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poet',
            options={'managed': True, 'verbose_name': 'poet', 'verbose_name_plural': 'poets'},
        ),
    ]
