# Generated by Django 5.2.11 on 2026-03-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_poet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='category',
            field=models.ForeignKey(db_column='cat_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poets', to='content.category'),
            preserve_default=False,
        ),
    ]
