# Generated by Django 5.2.11 on 2026-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_poet_category_poet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='photo',
            field=models.ImageField(blank=True, help_text='Portrait of the poet', null=True, upload_to=''),
        ),
    ]
