# Generated by Django 5.2.11 on 2026-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_poet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='is_selected',
            field=models.BooleanField(db_index=True, default=False, help_text='Show in the featured list on the home page for quick access.', verbose_name='selected for home'),
        ),
    ]
